name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Docker login
      run: docker login docker.pkg.github.com -u qautomatron -p ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build image
      run: docker build -t docker.pkg.github.com/qautomatron/docker-android/api29:0.1 .
      
